--------------------------------------------------------
--  File created - Saturday-November-25-2023   
--------------------------------------------------------
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER SCHOOL_HERRERA_2232086 IDENTIFIED BY 123;

GRANT CONNECT, RESOURCE TO SCHOOL_HERRERA_2232086;

GRANT UNLIMITED TABLESPACE TO SCHOOL_HERRERA_2232086;

ALTER SESSION SET CURRENT_SCHEMA = SCHOOL_HERRERA_2232086;

--------------------------------------------------------
--  DDL for Type TYPE_REPORT_STUDENT_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_REPORT_STUDENT_ROW" AS OBJECT
    /* 2023-11-10  NATALIA HERRERA( 2232086)
     CREATE A NEW TYPE */
     /* 2023-11-24  NATALIA HERRERA( 2232086)
     add allergies*/
     (
        report_id                VARCHAR2(32 BYTE),
        grade                    NUMBER(3, 0),
        comments                 VARCHAR2(250 BYTE),
        report_create_date_time  TIMESTAMP(6),
        report_modify_date_time  TIMESTAMP(6),
        dates_exam               DATE,
        student_id               VARCHAR2(32 BYTE),
        student_lastname         VARCHAR2(20 BYTE),
        student_firstname        VARCHAR2(20 BYTE),
        student_number           NUMBER(9, 0),
        address                  VARCHAR2(50 BYTE),
        city                     VARCHAR2(20 BYTE),
        postal_code              VARCHAR2(6 BYTE),
        student_create_date_time TIMESTAMP(6),
        student_modify_date_time TIMESTAMP(6),
        numbers_of_tries         NUMBER(2, 0),
        allergies                VARCHAR2(30),
        teacher_id               VARCHAR2(32 BYTE),
        teacher_lastname         VARCHAR2(20 BYTE),
        teacher_firstname        VARCHAR2(20 BYTE),
        email                    VARCHAR2(50 BYTE),
        salary                   NUMBER(5, 2),
        teacher_create_date_time TIMESTAMP(6),
        teacher_modify_date_time TIMESTAMP(6),
        insurance_number         NUMBER(9, 0),
        insurances_fee           NUMBER(4, 2),
        insurance_to_pay         NUMBER(6, 2),
        course_id                VARCHAR2(32 BYTE),
        course_name              VARCHAR2(25 BYTE),
        course_code              VARCHAR2(10 BYTE),
        description              VARCHAR2(4000 BYTE),
        course_create_date_time  TIMESTAMP(6),
        course_modify_date_time  TIMESTAMP(6)
    
)

/
--------------------------------------------------------
--  DDL for Type TYPE_REPORT_STUDENT_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_REPORT_STUDENT_TABLE" 
AS TABLE OF type_report_student_row
/* 2023-11-10  NATALIA HERRERA( 2232086)
     CREATE A NEW TYPE */
     /* 2023-11-24  NATALIA HERRERA( 2232086)
     drop and created again to add allergies*/;

/
--------------------------------------------------------
--  DDL for Type TYPE_STUDENTS_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_STUDENTS_ROW" AS OBJECT 
/* 2023-11-01  NATALIA HERRERA( 2232086)
    CREATE TYPE FOR PROCEDURE
    2023-11-24  NATALIA HERRERA( 2232086)
    ADD ALLERGIES COLUMN
    */ 
( 
    STUDENT_ID	VARCHAR2(32 BYTE),
    LASTNAME	VARCHAR2(20 BYTE),
    FIRSTNAME	VARCHAR2(20 BYTE),
    ADDRESS	VARCHAR2(40 BYTE),
    CITY	VARCHAR2(15 BYTE),
    POSTAL_CODE	VARCHAR2(6 BYTE),
    STUDENT_NUMBER	NUMBER(9,0),
    CREATE_DATE_TIME	TIMESTAMP(6),
    MODIFY_DATE_TIME	TIMESTAMP(6),
    ALLERGIES VARCHAR2(30)
)

/
--------------------------------------------------------
--  DDL for Type TYPE_STUDENTS_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_STUDENTS_TABLE" 
AS TABLE OF TYPE_STUDENTS_ROW

/* 2023-11-02  NATALIA HERRERA( 2232086)
    DROP TYPE AND CREATE A NEW TYPE FOR CHANGE THE NAME FOR LASTNAME
    2023-11-24  NATALIA HERRERA( 2232086)
    ADD ALLERGIES COLUMN*/ ;

/
--------------------------------------------------------
--  DDL for Type TYPE_TEACHERS_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_TEACHERS_ROW" AS OBJECT 
/* 2023-11-01  NATALIA HERRERA( 2232086)
    CREATE TYPE FOR PROCEDURE*/ 
( 
    TEACHER_ID	VARCHAR2(32 BYTE),
    LASTNAME	VARCHAR2(20 BYTE),
    FIRSTNAME	VARCHAR2(20 BYTE),
    EMAIL	VARCHAR2(20 BYTE),
    SALARY	NUMBER(5,2),
    CREATE_DATE_TIME	TIMESTAMP(6),
    MODIFY_DATE_TIME	TIMESTAMP(6)
  
)

/
--------------------------------------------------------
--  DDL for Type TYPE_TEACHERS_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_TEACHERS_TABLE" 
AS TABLE OF TYPE_TEACHERS_ROW/* 2023-11-02  NATALIA HERRERA( 2232086)
    CREATE A NEW TYPE */ ;

/
--------------------------------------------------------
--  DDL for Type TYPE_TIMESHEET_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_TIMESHEET_ROW" AS OBJECT 
/* 2023-11-10  NATALIA HERRERA( 2232086)
    CREATE TYPE ROW*/ (
        timesheet_id        VARCHAR2(32 BYTE),
        teacher_id          VARCHAR2(32 BYTE),
        week_number         NUMBER(2, 0),
        year                NUMBER(4, 0),
        number_hours_worked NUMBER(3, 1),
        create_date_time    TIMESTAMP(6),
        modify_date_time    TIMESTAMP(6)
)

/
--------------------------------------------------------
--  DDL for Type TYPE_TIMESHEET_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_TIMESHEET_TABLE" 
AS TABLE OF TYPE_TIMESHEET_ROW/* 2023-11-10  NATALIA HERRERA( 2232086)
    DROP TYPE AND CREATE A NEW TYPE FOR CHANGE THE NAME FOR LASTNAME*/ ;

/
--------------------------------------------------------
--  DDL for Type TYPE_TIMESHEET_TEACHER_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_TIMESHEET_TEACHER_ROW" AS OBJECT
/* 2023-11-01  NATALIA HERRERA( 2232086)
    CREATE TYPE FOR PROCEDURE
    2023-11-24  NATALIA HERRERA( 2232086)
    ADD FIELD PAYCHECK
    */ (
        timesheet_id           VARCHAR2(32 BYTE),
        week_number            NUMBER(2, 0),
        year                   NUMBER(4, 0),
        number_of_hours_worked NUMBER(3, 1),
        timesheet_create_date_time       TIMESTAMP(6),
        timesheet_modify_date_time       TIMESTAMP(6),
        teacher_id             VARCHAR2(32 BYTE),
        last_name              VARCHAR2(20 BYTE),
        first_name             VARCHAR2(20 BYTE),
        email                  VARCHAR2(50 BYTE),
        salary                 NUMBER(5, 2),
        teacher_create_date_time       TIMESTAMP(6),
        teacher_modify_date_time       TIMESTAMP(6),
        insurance_number       NUMBER(9, 0),
        insurances_fee         NUMBER(4, 2),
        insurance_pay          NUMBER(6, 2),
        PAYCHECK               NUMBER (9,2)
)

/
--------------------------------------------------------
--  DDL for Type TYPE_TIMESHEET_TEACHER_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCHOOL_HERRERA_2232086"."TYPE_TIMESHEET_TEACHER_TABLE" 
AS TABLE OF type_timesheet_teacher_row/* 2023-11-10  NATALIA HERRERA( 2232086)
   CREATE A NEW TYPE
   2023-11-24  NATALIA HERRERA( 2232086)
   DROP AND CREATE AGAIN BECAUSE OF THE PAYCHECK*/;

/
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_COURSE_PK
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL_HERRERA_2232086"."SEQUENCE_COURSE_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_STUDENT_NUMBER
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL_HERRERA_2232086"."SEQUENCE_STUDENT_NUMBER"  MINVALUE 85 MAXVALUE 9999999999999 INCREMENT BY 5 START WITH 186 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table COURSES
--------------------------------------------------------

  CREATE TABLE "SCHOOL_HERRERA_2232086"."COURSES" 
   (	"COURSE_ID" VARCHAR2(32 BYTE) DEFAULT NULL, 
	"COURSE_NAME" VARCHAR2(25 BYTE), 
	"COURSE_CODE" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."COURSES"."COURSE_ID" IS ' 2023-11-03  NATALIA HERRERA( 2232086)
DROP PREVIOUS AND CREATE A NEW ONE WITH DESCRIPTION VARCHAR
2023-11-17 NATALIA HERRERA( 2232086) ALTER TABLE ADD SEQUENCE PK';
--------------------------------------------------------
--  DDL for Table MODIFICATIONS_HISTORY
--------------------------------------------------------

  CREATE TABLE "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY" 
   (	"FIELD_NAME" VARCHAR2(50 BYTE), 
	"MODIFICATION_DATE" DATE, 
	"OLD_VALUE" VARCHAR2(32 BYTE), 
	"NEW_VALUE" VARCHAR2(32 BYTE), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"REPORT_ID" VARCHAR2(32 BYTE), 
	"MODIFICATION_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID()
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY"."FIELD_NAME" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
CREATE NEW TABLE 2023-11-17 NATALIA HERRERA( 2232086)
MODIFICATION OF THE TABLE, ADDING NEW COULNS';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY"."REPORT_ID" IS ' 2023-11-17  NATALIA HERRERA( 2232086)
ADD NEW COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY"."MODIFICATION_ID" IS ' 2023-11-17  NATALIA HERRERA( 2232086)
ADD NEW COLUMN';
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "SCHOOL_HERRERA_2232086"."REPORTS" 
   (	"REPORT_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"STUDENT_ID" VARCHAR2(32 BYTE), 
	"TEACHER_ID" VARCHAR2(32 BYTE), 
	"GRADE" NUMBER(3,0), 
	"COMMENTS" VARCHAR2(250 BYTE), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"DATES_EXAM" DATE, 
	"COURSE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."REPORT_ID" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created the REPORTS table
 2023-11-01  NATALIA HERRERA( 2232086)
ALTER TABLE CREATE NEW COLUMN
 2023-11-01  NATALIA HERRERA( 2232086)
ALTER TABLE Created NEW CONSTRAINT';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."STUDENT_ID" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."TEACHER_ID" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."GRADE" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."COMMENTS" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."CREATE_DATE_TIME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."MODIFY_DATE_TIME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."DATES_EXAM" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
ADD NEW COLUMN
';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."REPORTS"."COURSE_ID" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
ALTER TABLE ADD NEW COLUMN
';
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" 
   (	"STUDENT_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(40 BYTE), 
	"CITY" VARCHAR2(15 BYTE), 
	"POSTAL_CODE" VARCHAR2(6 BYTE), 
	"STUDENT_NUMBER" VARCHAR2(11 BYTE), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"NUMBERS_OF_TRIES" NUMBER(2,0), 
	"ALLERGIES" VARCHAR2(30 CHAR) DEFAULT 'DONT HAVE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."STUDENT_ID" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created the STUDENTS table';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."LASTNAME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN
2023-11-02  NATALIA HERRERA( 2232086)
   UPDATE NAME FOR LASTNAME';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."FIRSTNAME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."ADDRESS" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."CITY" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."POSTAL_CODE" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."STUDENT_NUMBER" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."CREATE_DATE_TIME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN FOR THE CREATION TIME OF THE ROW';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."MODIFY_DATE_TIME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
MODIFY COLUMN FOR THE CREATION TIME OF THE ROW';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."NUMBERS_OF_TRIES" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
ADD COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."STUDENTS"."ALLERGIES" IS ' 2023-11-24  NATALIA HERRERA( 2232086)
ADD NEW COLUMN';
--------------------------------------------------------
--  DDL for Table TEACHERS
--------------------------------------------------------

  CREATE TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" 
   (	"TEACHER_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER(5,2), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"INSURANCE_NUMBER" NUMBER(9,0), 
	"INSURANCE_TO_PAY" NUMBER(6,2), 
	"INSURANCES_FEE" NUMBER(4,2) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."TEACHER_ID" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created the TEACHERS table';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."LASTNAME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN
2023-11-02  NATALIA HERRERA( 2232086)
   UPDATE NAME FOR LASTNAME';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."FIRSTNAME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."EMAIL" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."SALARY" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."CREATE_DATE_TIME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN FOR THE CREATION TIME OF THE ROW';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."MODIFY_DATE_TIME" IS ' 2023-11-01  NATALIA HERRERA( 2232086)
Created COLUMN FOR THE MODIFICATION TIME OF THE ROW';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."INSURANCE_NUMBER" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."INSURANCE_TO_PAY" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
Created COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TEACHERS"."INSURANCES_FEE" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
Created COLUMN';
--------------------------------------------------------
--  DDL for Table TIMESHEET
--------------------------------------------------------

  CREATE TABLE "SCHOOL_HERRERA_2232086"."TIMESHEET" 
   (	"TIMESHEET_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"TEACHER_ID" VARCHAR2(32 BYTE), 
	"WEEK_NUMBER" NUMBER(2,0), 
	"YEAR" NUMBER(4,0), 
	"NUMBER_HOURS_WORKED" NUMBER(3,1), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TIMESHEET"."TIMESHEET_ID" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
CREATE NEW TABLE';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TIMESHEET"."TEACHER_ID" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
ADD COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TIMESHEET"."WEEK_NUMBER" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
ADD COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TIMESHEET"."YEAR" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
ADD COLUMN';
   COMMENT ON COLUMN "SCHOOL_HERRERA_2232086"."TIMESHEET"."NUMBER_HOURS_WORKED" IS ' 2023-11-10  NATALIA HERRERA( 2232086)
ADD COLUMN';
REM INSERTING into SCHOOL_HERRERA_2232086.COURSES
SET DEFINE OFF;
Insert into SCHOOL_HERRERA_2232086.COURSES (COURSE_ID,COURSE_NAME,COURSE_CODE,DESCRIPTION,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('086F206ED41E46968C1686300D181623','INFORMATION SYSTEM','420-AS2-AS','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',to_timestamp('23-11-03 18:24:03.607409000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-03 18:24:06.856000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCHOOL_HERRERA_2232086.COURSES (COURSE_ID,COURSE_NAME,COURSE_CODE,DESCRIPTION,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('F8AAB17ABA674680AB6D3CACBA32FC13','DATABASES II','420-BD2-AS','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',to_timestamp('23-11-03 18:26:33.798386000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-03 18:26:38.932000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCHOOL_HERRERA_2232086.COURSES (COURSE_ID,COURSE_NAME,COURSE_CODE,DESCRIPTION,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('1D154DB2FE214507905A8ACAA72841BD','WEB CLIENT DEVELOPMENT','420-DW2-AS','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',to_timestamp('23-11-03 18:27:13.809227000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-03 18:27:16.576000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCHOOL_HERRERA_2232086.COURSES (COURSE_ID,COURSE_NAME,COURSE_CODE,DESCRIPTION,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('A79D868055904E2EA84E6DF844BEE2A4','OPERATING SYSTEMS','420-SE2-AS','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',to_timestamp('23-11-12 16:35:55.413000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:35:55.413000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCHOOL_HERRERA_2232086.COURSES (COURSE_ID,COURSE_NAME,COURSE_CODE,DESCRIPTION,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('7630A786A4B44B7E9A98A28DD8129B41','OO PROGRAMMING','420-CT2-AS','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',to_timestamp('23-11-12 16:36:54.509000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:36:54.509000000','RR-MM-DD HH24:MI:SSXFF'));
REM INSERTING into SCHOOL_HERRERA_2232086.MODIFICATIONS_HISTORY
SET DEFINE OFF;
Insert into SCHOOL_HERRERA_2232086.MODIFICATIONS_HISTORY (FIELD_NAME,MODIFICATION_DATE,OLD_VALUE,NEW_VALUE,CREATE_DATE_TIME,MODIFY_DATE_TIME,REPORT_ID,MODIFICATION_ID) values ('GRADE',to_date('23-11-12','RR-MM-DD'),'92','10',null,to_timestamp('23-11-17 19:18:54.176000000','RR-MM-DD HH24:MI:SSXFF'),null,'F8B0C2B7709F435C851D89F4306DD423');
Insert into SCHOOL_HERRERA_2232086.MODIFICATIONS_HISTORY (FIELD_NAME,MODIFICATION_DATE,OLD_VALUE,NEW_VALUE,CREATE_DATE_TIME,MODIFY_DATE_TIME,REPORT_ID,MODIFICATION_ID) values ('COMMENTS',to_date('23-11-12','RR-MM-DD'),'Lorem Ipsum is simply dummy text','NICE',null,to_timestamp('23-11-17 19:18:54.176000000','RR-MM-DD HH24:MI:SSXFF'),null,'68B274D3F8DD42FFB51229D43436CA90');
Insert into SCHOOL_HERRERA_2232086.MODIFICATIONS_HISTORY (FIELD_NAME,MODIFICATION_DATE,OLD_VALUE,NEW_VALUE,CREATE_DATE_TIME,MODIFY_DATE_TIME,REPORT_ID,MODIFICATION_ID) values ('EXAME_DATE',to_date('23-11-12','RR-MM-DD'),'23-12-12','23-12-12',null,to_timestamp('23-11-17 19:18:54.176000000','RR-MM-DD HH24:MI:SSXFF'),null,'14DFA41E170B4E69A240DF948C49E580');
Insert into SCHOOL_HERRERA_2232086.MODIFICATIONS_HISTORY (FIELD_NAME,MODIFICATION_DATE,OLD_VALUE,NEW_VALUE,CREATE_DATE_TIME,MODIFY_DATE_TIME,REPORT_ID,MODIFICATION_ID) values ('GRADE',to_date('23-11-25','RR-MM-DD'),'10','83',to_timestamp('23-11-25 00:34:33.454000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-25 00:34:33.454000000','RR-MM-DD HH24:MI:SSXFF'),'62B378BC48754F40A3D7FCD21D9C1462','2D758146632B4FB3818C89A6FD322CC1');
Insert into SCHOOL_HERRERA_2232086.MODIFICATIONS_HISTORY (FIELD_NAME,MODIFICATION_DATE,OLD_VALUE,NEW_VALUE,CREATE_DATE_TIME,MODIFY_DATE_TIME,REPORT_ID,MODIFICATION_ID) values ('COMMENTS',to_date('23-11-25','RR-MM-DD'),'NICE','GOOD',to_timestamp('23-11-25 00:34:33.456000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-25 00:34:33.456000000','RR-MM-DD HH24:MI:SSXFF'),'62B378BC48754F40A3D7FCD21D9C1462','9DD040829D11423BA9AB3CC95F1F95AA');
Insert into SCHOOL_HERRERA_2232086.MODIFICATIONS_HISTORY (FIELD_NAME,MODIFICATION_DATE,OLD_VALUE,NEW_VALUE,CREATE_DATE_TIME,MODIFY_DATE_TIME,REPORT_ID,MODIFICATION_ID) values ('EXAME_DATE',to_date('23-11-25','RR-MM-DD'),'23-12-12','23-10-15',to_timestamp('23-11-25 00:34:33.457000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-25 00:34:33.457000000','RR-MM-DD HH24:MI:SSXFF'),'62B378BC48754F40A3D7FCD21D9C1462','78D63D1D40C7495CB778E76926E1CB6D');
REM INSERTING into SCHOOL_HERRERA_2232086.REPORTS
SET DEFINE OFF;
Insert into SCHOOL_HERRERA_2232086.REPORTS (REPORT_ID,STUDENT_ID,TEACHER_ID,GRADE,COMMENTS,CREATE_DATE_TIME,MODIFY_DATE_TIME,DATES_EXAM,COURSE_ID) values ('47C1EAEEC7B54C12B969CCAF37D3E50D','A8A9E455244040789BE43D20D25300B5','DAAF3707D4DA45A3B917841AB553723E',89,'Lorem Ipsum is simply dummy text',to_timestamp('23-11-02 15:44:32.338702000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 15:51:39.179000000','RR-MM-DD HH24:MI:SSXFF'),to_date('23-12-13','RR-MM-DD'),'086F206ED41E46968C1686300D181623');
Insert into SCHOOL_HERRERA_2232086.REPORTS (REPORT_ID,STUDENT_ID,TEACHER_ID,GRADE,COMMENTS,CREATE_DATE_TIME,MODIFY_DATE_TIME,DATES_EXAM,COURSE_ID) values ('62B378BC48754F40A3D7FCD21D9C1462','20D41AB7204045DD9ADD6A6A17832479','F18A6562C33E435998496862DBB9472D',83,'GOOD',to_timestamp('23-11-02 15:45:08.229354000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-25 00:34:33.448000000','RR-MM-DD HH24:MI:SSXFF'),to_date('23-10-15','RR-MM-DD'),'1D154DB2FE214507905A8ACAA72841BD');
Insert into SCHOOL_HERRERA_2232086.REPORTS (REPORT_ID,STUDENT_ID,TEACHER_ID,GRADE,COMMENTS,CREATE_DATE_TIME,MODIFY_DATE_TIME,DATES_EXAM,COURSE_ID) values ('50395AFC151F4009BD2D01EB4E592101','DB20A9AF37664CBCA068AC7D10773837','FE2EBF3BE4EB46D8B6E1BF6051A6BA5F',75,'Lorem Ipsum is simply dummy text',to_timestamp('23-11-02 15:45:37.508629000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 15:51:39.181000000','RR-MM-DD HH24:MI:SSXFF'),to_date('23-12-19','RR-MM-DD'),'F8AAB17ABA674680AB6D3CACBA32FC13');
Insert into SCHOOL_HERRERA_2232086.REPORTS (REPORT_ID,STUDENT_ID,TEACHER_ID,GRADE,COMMENTS,CREATE_DATE_TIME,MODIFY_DATE_TIME,DATES_EXAM,COURSE_ID) values ('366040709E984E4EA19B40DB66F28D7E','2B30694B76754DFD8FFE30587E089FA1','01F52954662B4E0781D95415A68709CF',80,'GOOD JOB',to_timestamp('23-11-12 16:46:55.778000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:46:55.778000000','RR-MM-DD HH24:MI:SSXFF'),to_date('23-11-12','RR-MM-DD'),'A79D868055904E2EA84E6DF844BEE2A4');
Insert into SCHOOL_HERRERA_2232086.REPORTS (REPORT_ID,STUDENT_ID,TEACHER_ID,GRADE,COMMENTS,CREATE_DATE_TIME,MODIFY_DATE_TIME,DATES_EXAM,COURSE_ID) values ('A921BDA1BB304D489C6925DA4F7D151B','3258D8D6A1CF4CC4B269912495C62956','06A179E27A3844A781E4516751FD0727',95,'EXCELENT',to_timestamp('23-11-12 16:48:22.544000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:48:22.544000000','RR-MM-DD HH24:MI:SSXFF'),to_date('23-11-12','RR-MM-DD'),'F8AAB17ABA674680AB6D3CACBA32FC13');
REM INSERTING into SCHOOL_HERRERA_2232086.STUDENTS
SET DEFINE OFF;
Insert into SCHOOL_HERRERA_2232086.STUDENTS (STUDENT_ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTAL_CODE,STUDENT_NUMBER,CREATE_DATE_TIME,MODIFY_DATE_TIME,NUMBERS_OF_TRIES,ALLERGIES) values ('A8A9E455244040789BE43D20D25300B5','HERRERA','NATALIA','6777 AVE MOUINTAIN SIGHTS','MONTREAL','H1H2H3',null,to_timestamp('23-11-02 13:52:18.788000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-24 19:39:35.009000000','RR-MM-DD HH24:MI:SSXFF'),null,null);
Insert into SCHOOL_HERRERA_2232086.STUDENTS (STUDENT_ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTAL_CODE,STUDENT_NUMBER,CREATE_DATE_TIME,MODIFY_DATE_TIME,NUMBERS_OF_TRIES,ALLERGIES) values ('3258D8D6A1CF4CC4B269912495C62956','OLIVEIRA','PAULO','123 cote des neiges','MONTREAL','2H2H3H',null,to_timestamp('23-11-12 16:12:00.974000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-24 19:39:35.009000000','RR-MM-DD HH24:MI:SSXFF'),1,null);
Insert into SCHOOL_HERRERA_2232086.STUDENTS (STUDENT_ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTAL_CODE,STUDENT_NUMBER,CREATE_DATE_TIME,MODIFY_DATE_TIME,NUMBERS_OF_TRIES,ALLERGIES) values ('66B20BB301CD4492932D0FCB0C85FF0B','GOMEZ','HAMILTON','6777 MOUNTAIN SIGHTS','MONTREAL','1H1H2H','STUDENT_91',to_timestamp('23-11-24 21:34:06.109000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-24 21:34:06.109000000','RR-MM-DD HH24:MI:SSXFF'),null,'PEANUTS');
Insert into SCHOOL_HERRERA_2232086.STUDENTS (STUDENT_ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTAL_CODE,STUDENT_NUMBER,CREATE_DATE_TIME,MODIFY_DATE_TIME,NUMBERS_OF_TRIES,ALLERGIES) values ('2B30694B76754DFD8FFE30587E089FA1','PENHA','NELSON','4452 Snowdown','MONTREAL','1D2D3D',null,to_timestamp('23-11-12 16:13:17.708000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-24 21:42:00.349000000','RR-MM-DD HH24:MI:SSXFF'),1,'MILK');
Insert into SCHOOL_HERRERA_2232086.STUDENTS (STUDENT_ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTAL_CODE,STUDENT_NUMBER,CREATE_DATE_TIME,MODIFY_DATE_TIME,NUMBERS_OF_TRIES,ALLERGIES) values ('DB20A9AF37664CBCA068AC7D10773837','MICAI','THAMIRIS','5567 ST SAINT JOSEPH','LAVAL','H3H1H3',null,to_timestamp('23-11-02 13:56:19.392000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-24 19:39:35.009000000','RR-MM-DD HH24:MI:SSXFF'),null,null);
Insert into SCHOOL_HERRERA_2232086.STUDENTS (STUDENT_ID,LASTNAME,FIRSTNAME,ADDRESS,CITY,POSTAL_CODE,STUDENT_NUMBER,CREATE_DATE_TIME,MODIFY_DATE_TIME,NUMBERS_OF_TRIES,ALLERGIES) values ('20D41AB7204045DD9ADD6A6A17832479','HANSEN','ANNA','6177 ST COTE DE NEIGES','MONTREAL','H5H1H4',null,to_timestamp('23-11-02 14:23:51.546000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-25 00:34:33.453000000','RR-MM-DD HH24:MI:SSXFF'),4,null);
REM INSERTING into SCHOOL_HERRERA_2232086.TEACHERS
SET DEFINE OFF;
Insert into SCHOOL_HERRERA_2232086.TEACHERS (TEACHER_ID,LASTNAME,FIRSTNAME,EMAIL,SALARY,CREATE_DATE_TIME,MODIFY_DATE_TIME,INSURANCE_NUMBER,INSURANCE_TO_PAY,INSURANCES_FEE) values ('F18A6562C33E435998496862DBB9472D','Saint','Patrick','Saint@lasalle.ca',150,to_timestamp('23-11-02 14:54:44.420000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-24 21:59:47.041000000','RR-MM-DD HH24:MI:SSXFF'),258741369,null,1.25);
Insert into SCHOOL_HERRERA_2232086.TEACHERS (TEACHER_ID,LASTNAME,FIRSTNAME,EMAIL,SALARY,CREATE_DATE_TIME,MODIFY_DATE_TIME,INSURANCE_NUMBER,INSURANCE_TO_PAY,INSURANCES_FEE) values ('DAAF3707D4DA45A3B917841AB553723E','Aghamirkarimi','Dara','Dara@lasalle.ca',435.98,to_timestamp('23-11-02 14:44:46.223000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 15:41:09.385000000','RR-MM-DD HH24:MI:SSXFF'),369852147,null,3.25);
Insert into SCHOOL_HERRERA_2232086.TEACHERS (TEACHER_ID,LASTNAME,FIRSTNAME,EMAIL,SALARY,CREATE_DATE_TIME,MODIFY_DATE_TIME,INSURANCE_NUMBER,INSURANCE_TO_PAY,INSURANCES_FEE) values ('FE2EBF3BE4EB46D8B6E1BF6051A6BA5F','Maftei','Mihai','Maftei@lasalle.ca',295.82,to_timestamp('23-11-02 14:52:58.352000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:32:15.643000000','RR-MM-DD HH24:MI:SSXFF'),275369841,null,2.58);
Insert into SCHOOL_HERRERA_2232086.TEACHERS (TEACHER_ID,LASTNAME,FIRSTNAME,EMAIL,SALARY,CREATE_DATE_TIME,MODIFY_DATE_TIME,INSURANCE_NUMBER,INSURANCE_TO_PAY,INSURANCES_FEE) values ('01F52954662B4E0781D95415A68709CF','Valentinov','Hristiyan','Hrist@lasalle.ca',100,to_timestamp('23-11-12 16:30:17.244000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:32:15.644000000','RR-MM-DD HH24:MI:SSXFF'),258741369,null,1.45);
Insert into SCHOOL_HERRERA_2232086.TEACHERS (TEACHER_ID,LASTNAME,FIRSTNAME,EMAIL,SALARY,CREATE_DATE_TIME,MODIFY_DATE_TIME,INSURANCE_NUMBER,INSURANCE_TO_PAY,INSURANCES_FEE) values ('06A179E27A3844A781E4516751FD0727','Parent','Jean-Fran�ois ','Jean@lasalle.ca',230,to_timestamp('23-11-12 16:31:18.875000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-25 01:10:07.411000000','RR-MM-DD HH24:MI:SSXFF'),123741369,55.5,1.85);
REM INSERTING into SCHOOL_HERRERA_2232086.TIMESHEET
SET DEFINE OFF;
Insert into SCHOOL_HERRERA_2232086.TIMESHEET (TIMESHEET_ID,TEACHER_ID,WEEK_NUMBER,YEAR,NUMBER_HOURS_WORKED,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('203C749638004E038779C7AE61DFC8BA','01F52954662B4E0781D95415A68709CF',32,2023,30,to_timestamp('23-11-12 16:51:29.917000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:53:31.093000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCHOOL_HERRERA_2232086.TIMESHEET (TIMESHEET_ID,TEACHER_ID,WEEK_NUMBER,YEAR,NUMBER_HOURS_WORKED,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('83FC9CFB089A4D1BAE8F8C2FED9A91D3','06A179E27A3844A781E4516751FD0727',10,2023,45,to_timestamp('23-11-12 16:52:04.596000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:52:04.596000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCHOOL_HERRERA_2232086.TIMESHEET (TIMESHEET_ID,TEACHER_ID,WEEK_NUMBER,YEAR,NUMBER_HOURS_WORKED,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('05F0F34BD6B845BC92680645A8C9616C','FE2EBF3BE4EB46D8B6E1BF6051A6BA5F',45,2023,37,to_timestamp('23-11-12 16:52:30.881000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:52:30.881000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCHOOL_HERRERA_2232086.TIMESHEET (TIMESHEET_ID,TEACHER_ID,WEEK_NUMBER,YEAR,NUMBER_HOURS_WORKED,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('C6AB98A31FF34D88A0450A0CBB29A5BB','DAAF3707D4DA45A3B917841AB553723E',48,2023,40,to_timestamp('23-11-12 16:52:49.588000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:52:49.588000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCHOOL_HERRERA_2232086.TIMESHEET (TIMESHEET_ID,TEACHER_ID,WEEK_NUMBER,YEAR,NUMBER_HOURS_WORKED,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('DC13B70220CF4A6C8CDF9D7AF446C24E','F18A6562C33E435998496862DBB9472D',38,2023,36,to_timestamp('23-11-12 16:53:09.114000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-11-12 16:53:09.114000000','RR-MM-DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index TEACHERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."TEACHERS_PK" ON "SCHOOL_HERRERA_2232086"."TEACHERS" ("TEACHER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPORTS_STUDENT_COURSE_ID_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."REPORTS_STUDENT_COURSE_ID_UK" ON "SCHOOL_HERRERA_2232086"."REPORTS" ("STUDENT_ID", "COURSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."STUDENTS_PK" ON "SCHOOL_HERRERA_2232086"."STUDENTS" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MODIFICATIONS_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY_PK" ON "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY" ("MODIFICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPORTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."REPORTS_PK" ON "SCHOOL_HERRERA_2232086"."REPORTS" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENTS_STUDENTNUMBER_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."STUDENTS_STUDENTNUMBER_UK" ON "SCHOOL_HERRERA_2232086"."STUDENTS" ("STUDENT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIMESHEET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."TIMESHEET_PK" ON "SCHOOL_HERRERA_2232086"."TIMESHEET" ("TIMESHEET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSES_COURSE_CODE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."COURSES_COURSE_CODE_UK" ON "SCHOOL_HERRERA_2232086"."COURSES" ("COURSE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIMESHEET_UK_TEACHER_WEEK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."TIMESHEET_UK_TEACHER_WEEK" ON "SCHOOL_HERRERA_2232086"."TIMESHEET" ("TEACHER_ID", "WEEK_NUMBER", "YEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL_HERRERA_2232086"."COURSES_PK" ON "SCHOOL_HERRERA_2232086"."COURSES" ("COURSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TG_COURSES_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_COURSES_MODIFY" 
BEFORE UPDATE ON COURSES 
FOR EACH ROW
BEGIN
/* 2023-11-03  NATALIA HERRERA( 2232086)
    CREATE TRIGGER FOR MODIFY THE DATA IN EACH TABLE*/ 
  :NEW.MODIFY_DATE_TIME := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_COURSES_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_COURSE_PK_SEQ
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_COURSE_PK_SEQ" BEFORE
    INSERT ON courses
    FOR EACH ROW
DECLARE
    valid_course_name VARCHAR2(2) := 'MS';
    action       VARCHAR2(20);
    vcourse_name VARCHAR2(20);
    date_trigger VARCHAR2(35) := to_char(sysdate, 'YYYY/MONTH/DD');
BEGIN
 /* 
  2023-11-17  NATALIA HERRERA( 2232086)
  CREATE SEQUENCE PK TRIGGER */

     IF upper(substr(:new.course_name, 1, 2)) = valid_course_name THEN
        :new.course_name := 'Microsoft'
                           || substr(:new.course_name, 3);
    END IF;
    
    IF inserting THEN
        action := 'Added';
        vcourse_name := :new.course_name;
    END IF;

    IF deleting THEN
        action := 'Deleted';
        vcourse_name := :old.course_name;
    END IF;

    dbms_output.put_line(action
                         || ' FOR COURSE '
                         || vcourse_name
                         || ' on '
                         || date_trigger);

END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_COURSE_PK_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_REPORTS_MODIFICATIONS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_REPORTS_MODIFICATIONS" AFTER
    UPDATE ON reports
    FOR EACH ROW
    
    DECLARE
    
    FCOUNT NUMBER:=0;
BEGIN

-- 2023-11-12  NATALIA HERRERA( 2232086)
-- CREATE A NEW TRIGGER MODIFICATION REPORTS
--2023-11-17  NATALIA HERRERA( 2232086)
-- MODIFICATION OF THE TRIGGER, ADD NEW FIELDS OF THE TABLES AND DBMS

    IF :old.report_id != :new.report_id THEN
        INSERT INTO modifications_history 
        (FIELD_NAME, MODIFICATION_DATE, OLD_VALUE, NEW_VALUE, REPORT_ID)
        VALUES (
            'REPORT_ID',
            sysdate,
            :old.report_id,
            :new.report_id,
            :new.report_id
        );
        
        FCOUNT:= FCOUNT +1;
        
    END IF;

    IF :old.student_id != :new.student_id THEN
        INSERT INTO modifications_history  (FIELD_NAME, MODIFICATION_DATE, OLD_VALUE, NEW_VALUE, REPORT_ID) VALUES (
            'STUDENT_ID',
            sysdate,
            :old.student_id,
            :new.student_id,
            :new.report_id
        );
    FCOUNT:= FCOUNT +1;
    END IF;

    IF :old.teacher_id != :new.teacher_id THEN
        INSERT INTO modifications_history  (FIELD_NAME, MODIFICATION_DATE, OLD_VALUE, NEW_VALUE, REPORT_ID) VALUES (
            'TEACHER_ID',
            sysdate,
            :old.teacher_id,
            :new.teacher_id,
            :new.report_id
        );
    FCOUNT:= FCOUNT +1;
    
    END IF;

    IF :old.grade != :new.grade THEN
        INSERT INTO modifications_history   (FIELD_NAME, MODIFICATION_DATE, OLD_VALUE, NEW_VALUE, REPORT_ID)VALUES (
            'GRADE',
            sysdate,
            :old.grade,
            :new.grade,
            :new.report_id
        );
    FCOUNT:= FCOUNT +1;
    END IF;

    IF :old.comments != :new.comments THEN
        INSERT INTO modifications_history  (FIELD_NAME, MODIFICATION_DATE, OLD_VALUE, NEW_VALUE, REPORT_ID) VALUES (
            'COMMENTS',
            sysdate,
            :old.comments,
            :new.comments,
            :new.report_id
        );
    FCOUNT:= FCOUNT +1;
    END IF;

    IF :old.dates_exam != :new.dates_exam THEN
        INSERT INTO modifications_history   (FIELD_NAME, MODIFICATION_DATE, OLD_VALUE, NEW_VALUE, REPORT_ID)VALUES (
            'EXAME_DATE',
            sysdate,
            :old.dates_exam,
            :new.dates_exam,
            :new.report_id
        );
    FCOUNT:= FCOUNT +1;
    END IF;
    
     IF :old.COURSE_ID != :new.COURSE_ID THEN
        INSERT INTO modifications_history   (FIELD_NAME, MODIFICATION_DATE, OLD_VALUE, NEW_VALUE, REPORT_ID)VALUES (
            'COURSE_ID',
            sysdate,
            :old.COURSE_ID,
            :new.COURSE_ID,
            :new.report_id
        );
    FCOUNT:= FCOUNT +1;
    END IF;

DBMS_OUTPUT.PUT_LINE('Total fields modified '|| FCOUNT );
END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_REPORTS_MODIFICATIONS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_REPORTS_MODIFICATIONS_GRADE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_REPORTS_MODIFICATIONS_GRADE" AFTER
    INSERT OR UPDATE OF GRADE ON reports
    FOR EACH ROW
BEGIN

-- 2023-11-03  NATALIA HERRERA( 2232086)
-- CREATE A NEW TRIGGER GRADE

 UPDATE students
  SET NUMBERS_OF_TRIES = nvl(NUMBERS_OF_TRIES,0) + 1
  where student_id = :NEW.STUDENT_ID;

END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_REPORTS_MODIFICATIONS_GRADE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_REPORTS_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_REPORTS_MODIFY" 
BEFORE UPDATE ON REPORTS 
FOR EACH ROW
BEGIN
/* 2023-11-02  NATALIA HERRERA( 2232086)
    CREATE TRIGGER FOR MODIFY THE DATA IN EACH TABLE*/ 
  :NEW.MODIFY_DATE_TIME := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_REPORTS_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_REPORT_ERROR_EXAM_DATE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_REPORT_ERROR_EXAM_DATE" BEFORE
    INSERT ON reports
    FOR EACH ROW
DECLARE
    vstudent_number NUMBER(3);
BEGIN

--2023-11-17  NATALIA HERRERA( 2232086)
-- CREATE NEW TRIGGER FOR ERROR

    IF :new.dates_exam > trunc(sysdate) THEN
       
        raise_application_error(-20001, 'Error number :'
                                        || vstudent_number
                                        || 'Exam date invalid: '
                                        || to_char(:new.dates_exam, 'DD/MONTH/YYYY'));

    END IF;
END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_REPORT_ERROR_EXAM_DATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_STUDENTS_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_STUDENTS_MODIFY" 
BEFORE UPDATE ON STUDENTS 
FOR EACH ROW
BEGIN
/* 2023-11-02  NATALIA HERRERA( 2232086)
    CREATE TRIGGER FOR MODIFY THE DATA IN EACH TABLE*/ 
  :NEW.MODIFY_DATE_TIME := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_STUDENTS_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_TEACHERS_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_TEACHERS_MODIFY" 
BEFORE UPDATE ON TEACHERS 
FOR EACH ROW
BEGIN
/* 2023-11-02  NATALIA HERRERA( 2232086)
    CREATE TRIGGER FOR MODIFY THE DATA IN EACH TABLE*/ 
  :NEW.MODIFY_DATE_TIME := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_TEACHERS_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_TIMESHEET_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_TIMESHEET_MODIFY" BEFORE
    UPDATE ON timesheet
    FOR EACH ROW
BEGIN
/* 2023-11-02  NATALIA HERRERA( 2232086)
    CREATE TRIGGER */
    :new.modify_date_time := current_timestamp;
END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_TIMESHEET_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_TIMESHEET_TEACHER_INSURANCE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHOOL_HERRERA_2232086"."TG_TIMESHEET_TEACHER_INSURANCE" 
AFTER UPDATE OF NUMBER_HOURS_WORKED ON TIMESHEET 
FOR EACH ROW 
BEGIN
-- 2023-11-10 NATALIA HERRERA( 2232086)
-- CREATE A NEW TRIGGER 

  update teachers
  set INSURANCE_TO_PAY = nvl(INSURANCES_FEE,0) * :NEW.NUMBER_HOURS_WORKED
  where teacher_id = :NEW.TEACHER_ID;
  
END;
/
ALTER TRIGGER "SCHOOL_HERRERA_2232086"."TG_TIMESHEET_TEACHER_INSURANCE" ENABLE;
--------------------------------------------------------
--  DDL for Procedure COURSE_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."COURSE_DELETE" (
    p_course_id IN VARCHAR2
) AS
BEGIN
 /* 2023-11-17  NATALIA HERRERA( 2232086)
  CREATE procedure delete*/
 
    DELETE courses
    WHERE course_id = p_course_id;
 
    COMMIT;
END course_delete;

/
--------------------------------------------------------
--  DDL for Procedure COURSE_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."COURSE_INSERT" (
    param_course_name IN VARCHAR2,
    param_course_code IN VARCHAR2,
    param_description IN VARCHAR2,
    param_course_id   OUT VARCHAR2
) AS
    new_course_name   VARCHAR2(30);
    vcourse_id        NUMBER;
BEGIN
 /* 2023-11-17  NATALIA HERRERA( 2232086)
  CREATE procedure insert*/

   

    SELECT
        sequence_course_pk.NEXTVAL
    INTO vcourse_id
    FROM
        dual;

    INSERT INTO courses (
        course_id,
        course_name,
        course_code,
        description
    ) VALUES (
        vcourse_id,
        param_course_name,
        param_course_code,
        param_description
    );

    COMMIT;
    param_course_id := vcourse_id;
END course_insert;

/
--------------------------------------------------------
--  DDL for Procedure REPORTS_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."REPORTS_DELETE" (
    param_student_id IN VARCHAR2,
    param_course_id  IN VARCHAR2
) AS
BEGIN
  /* 2023-11-10  NATALIA HERRERA( 2232086)
   CREATE DELETE PROCEDURE FOR REPORTS  */

    DELETE reports
    WHERE
            student_id = param_student_id
        AND course_id = param_course_id;

    COMMIT;
END reports_delete;

/
--------------------------------------------------------
--  DDL for Procedure REPORT_COUNT_GRADE_STUDENT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."REPORT_COUNT_GRADE_STUDENT" 
(
  PARAM_STUDENT_ID IN VARCHAR2 
, PARAM_COUNT OUT NUMBER 
) AS 
BEGIN
--2023-11-17  NATALIA HERRERA( 2232086)
-- CREATE PROCEDURE TO COUNT THE MARKS

  SELECT COUNT(1)
  INTO PARAM_COUNT
  FROM REPORTS
  WHERE STUDENT_ID = PARAM_STUDENT_ID;
  
END REPORT_COUNT_GRADE_STUDENT;

/
--------------------------------------------------------
--  DDL for Procedure REPORTS_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."REPORTS_INSERT" (
    param_student_id IN VARCHAR2,
    param_teacher_id IN VARCHAR2,
    param_grade      IN NUMBER,
    param_comments   IN VARCHAR2,
    param_dates_exam IN DATE,
    param_course_id  IN VARCHAR2
) AS
    param_count     NUMBER := 0;
    vstudent_number NUMBER;
    full_name       VARCHAR2(50);
BEGIN
  /* 2023-11-10  NATALIA HERRERA( 2232086)
   CREATE INSERT PROCEDURE FOR REPORTS 
   2023-11-12  NATALIA HERRERA( 2232086)
  ADD COURSE ID FIELD 
  2023-11-17  NATALIA HERRERA( 2232086)
  ADD count of grades */

    report_count_grade_student(param_student_id, param_count);
    IF param_count > 20 THEN
        SELECT student_number, 
            firstname
            || ' '
            || lastname
        INTO
            vstudent_number,
            full_name
        FROM
            students
        WHERE
            student_id = param_student_id;

        raise_application_error(-20001, 'The Student '
                                        || full_name
                                        || ' Student Number : '
                                        || vstudent_number
                                        || ' has reach the number maximum of grades. Error 086');
    ELSE
        INSERT INTO reports (
            student_id,
            teacher_id,
            grade,
            comments,
            dates_exam,
            course_id
        ) VALUES (
            param_student_id,
            param_teacher_id,
            param_grade,
            param_comments,
            param_dates_exam,
            param_course_id
        );

        COMMIT;
    END IF;

END reports_insert;

/

--------------------------------------------------------
--  DDL for Procedure REPORT_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."REPORT_UPDATE" (
    PARAM_report_id  IN VARCHAR2,
    PARAM_grade      IN NUMBER,
    PARAM_comments   IN VARCHAR2,
    PARAM_DATES_EXAM IN DATE
) AS
BEGIN
 /* 2023-11-10  NATALIA HERRERA( 2232086)
   CREATE DELETE PROCEDURE FOR REPORTS  */
 
    UPDATE reports
    SET grade = PARAM_grade,
        comments = PARAM_comments,
        DATES_EXAM = PARAM_DATES_EXAM
    WHERE
        report_id = PARAM_report_id;
 
    COMMIT;
END report_update;

/
--------------------------------------------------------
--  DDL for Procedure STUDENTS_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."STUDENTS_DELETE" 
( PARAM_STUDENT_ID IN VARCHAR2
) AS 
BEGIN
  /* 2023-11-01  NATALIA HERRERA( 2232086)
   CREATE DELETE PROCEDURE FOR STUDENTS TABLE  */
  
  DELETE STUDENTS
    WHERE STUDENT_ID = PARAM_STUDENT_ID;
    
    COMMIT;

END STUDENTS_DELETE;

/
--------------------------------------------------------
--  DDL for Procedure STUDENTS_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."STUDENTS_INSERT" 
(
  PARAM_LASTNAME IN VARCHAR2 
, PARAM_FIRSTNAME IN VARCHAR2 
, PARAM_ADDRESS IN VARCHAR2 
, PARAM_CITY IN VARCHAR2 
, PARAM_POSTAL_CODE IN VARCHAR2 
, PARAM_ALLERGIES IN VARCHAR2
) AS 

validation_allergies varchar2(30):= 'PEANUTS';
v_allergies varchar(30);
V_STUDENTNUMBER VARCHAR2(11):= 'STUDENT_';
V_SEQ VARCHAR2(3);
BEGIN
  /* 2023-11-01  NATALIA HERRERA( 2232086)
   CREATE INSERT PROCEDURE FOR STUDENTS TABLE 
   2023-11-02  NATALIA HERRERA( 2232086)
   UPDATE NAME FOR LASTNAME 
   2023-11-24  NATALIA HERRERA( 2232086)
   UPDATE WITH NEW COLUMNS(ALLERGIES), PEANUTS RVALIDATION AND STUDENT NUMBER */
  
     IF UPPER(TRIM(PARAM_ALLERGIES)) = validation_allergies THEN
    v_allergies:= UPPER(TRIM(PARAM_ALLERGIES));
    else
    v_allergies := PARAM_ALLERGIES;
    end if;
    
    
    SELECT
        sequence_STUDENT_NUMBER.NEXTVAL
    INTO v_SEQ
    FROM
        dual;
    
  INSERT INTO STUDENTS
    (LASTNAME,
    FIRSTNAME,
    ADDRESS,
    CITY,
    POSTAL_CODE,
    STUDENT_NUMBER,
    ALLERGIES)
    
    VALUES( PARAM_LASTNAME, 
    PARAM_FIRSTNAME, 
    PARAM_ADDRESS, 
    PARAM_CITY, 
    PARAM_POSTAL_CODE, 
    V_STUDENTNUMBER||V_SEQ,
    v_allergies);

    COMMIT;

END STUDENTS_INSERT;

/
--------------------------------------------------------
--  DDL for Procedure STUDENTS_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."STUDENTS_UPDATE" 
( PARAM_STUDENT_ID IN VARCHAR2,
  PARAM_LASTNAME IN VARCHAR2,
  PARAM_FIRSTNAME IN VARCHAR2,
  PARAM_ADDRESS IN VARCHAR2,
  PARAM_CITY IN VARCHAR2,
  PARAM_POSTAL_CODE IN VARCHAR2,
  PARAM_ALLERGIES IN VARCHAR2
) AS 
BEGIN
  /* 2023-11-01  NATALIA HERRERA( 2232086)
   CREATE UPDATE PROCEDURE FOR STUDENTS TABLE
   NOT INCLUDE THE STUDENT NUMBER 
    2023-11-02  NATALIA HERRERA( 2232086)
   UPDATE NAME FOR LASTNAME
   2023-11-02  NATALIA HERRERA( 2232086)
   UPDATE ADD ALLERGIES*/
  
  UPDATE STUDENTS
    SET LASTNAME = PARAM_LASTNAME,
    FIRSTNAME = PARAM_FIRSTNAME,
    ADDRESS = PARAM_ADDRESS,
    CITY = PARAM_CITY,
    POSTAL_CODE = PARAM_POSTAL_CODE,
    ALLERGIES = PARAM_ALLERGIES
    WHERE STUDENT_ID = PARAM_STUDENT_ID;
    
    COMMIT;

END STUDENTS_UPDATE;

/
--------------------------------------------------------
--  DDL for Procedure TEACHERS_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."TEACHERS_DELETE" 
( PARAM_TEACHER_ID IN VARCHAR2
) AS 
BEGIN
  /* 2023-11-01  NATALIA HERRERA( 2232086)
   CREATE DELETE PROCEDURE FOR TEACHERS TABLE  */
  
  DELETE TEACHERS
    WHERE TEACHER_ID = PARAM_TEACHER_ID;
    
    COMMIT;

END TEACHERS_DELETE;

/
--------------------------------------------------------
--  DDL for Procedure TEACHERS_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."TEACHERS_INSERT" 
(
  PARAM_LASTNAME IN VARCHAR2 
, PARAM_FIRSTNAME IN VARCHAR2 
, PARAM_EMAIL IN VARCHAR2 
, PARAM_SALARY IN NUMBER
, PARAM_INSURANCE_NUMBER	NUMBER
, PARAM_INSURANCES_FEE	NUMBER
) AS 
BEGIN
  /* 2023-11-01  NATALIA HERRERA( 2232086)
   CREATE INSERT PROCEDURE FOR TEACHERS TABLE 
    2023-11-02  NATALIA HERRERA( 2232086)
   UPDATE NAME FOR LASTNAME
      2023-11-12  NATALIA HERRERA( 2232086)
   UPDATE TO ADD INSURANCE NUMBER AND INSURANCE FEE*/
  
  
  INSERT INTO TEACHERS
    (LASTNAME,
    FIRSTNAME,
    EMAIL,
    SALARY,
    INSURANCE_NUMBER,
    INSURANCES_FEE)
    
    VALUES( PARAM_LASTNAME, 
    PARAM_FIRSTNAME, 
    PARAM_EMAIL, 
    PARAM_SALARY,
    PARAM_INSURANCE_NUMBER,
    PARAM_INSURANCES_FEE);

    COMMIT;

END TEACHERS_INSERT;

/
--------------------------------------------------------
--  DDL for Procedure TEACHERS_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."TEACHERS_UPDATE" 
( PARAM_TEACHER_ID IN VARCHAR2,
  PARAM_LASTNAME IN VARCHAR2,
  PARAM_FIRSTNAME IN VARCHAR2,
  PARAM_EMAIL IN VARCHAR2,
  PARAM_SALARY IN NUMBER
) AS 
BEGIN
  /* 2023-11-01  NATALIA HERRERA( 2232086)
   CREATE UPDATE PROCEDURE FOR TEACHERS TABLE 
    2023-11-02  NATALIA HERRERA( 2232086)
   UPDATE NAME FOR LASTNAME */
   
  
  UPDATE TEACHERS
    SET LASTNAME = PARAM_LASTNAME,
    FIRSTNAME = PARAM_FIRSTNAME,
    EMAIL = PARAM_EMAIL,
    SALARY = PARAM_SALARY
    WHERE TEACHER_ID = PARAM_TEACHER_ID;
    
    COMMIT;

END TEACHERS_UPDATE;

/
--------------------------------------------------------
--  DDL for Procedure TIMESHEET_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."TIMESHEET_DELETE" (
    PARAM_TEACHER_ID     IN VARCHAR2,
    PARAM_WEEK_NUMBER    IN NUMBER,
    PARAM_YEAR           IN NUMBER
) AS 
BEGIN
 /* 2023-11-10  NATALIA HERRERA( 2232086)
   CREATE DELETE PROCEDURE FOR TIMESHEET TABLE
  */
 
    DELETE timesheet N
    WHERE N.teacher_id = PARAM_TEACHER_ID
    AND N.year = PARAM_YEAR
    AND N.week_number = PARAM_WEEK_NUMBER;
 
    COMMIT;
 
END TIMESHEET_DELETE;

/
--------------------------------------------------------
--  DDL for Procedure TIMESHEET_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."TIMESHEET_INSERT" 
( PARAM_TEACHER_ID IN VARCHAR2,
PARAM_WEEK_NUMBER IN NUMBER,
PARAM_YEAR IN NUMBER,
PARAM_NUMBER_HOURS_WORKED IN NUMBER
) AS 
BEGIN
  /* 2023-11-10  NATALIA HERRERA( 2232086)
   CREATE DELETE PROCEDURE FOR TIMESHEET  */
  
 INSERT INTO TIMESHEET T (
        teacher_id,
        week_number,
        T.YEAR,
        T.NUMBER_HOURS_WORKED
    ) VALUES (
        PARAM_TEACHER_ID,
        PARAM_WEEK_NUMBER,
        PARAM_YEAR,
        PARAM_NUMBER_HOURS_WORKED
    );
    COMMIT;
END TIMESHEET_INSERT;

/
--------------------------------------------------------
--  DDL for Procedure TIMESHEET_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHOOL_HERRERA_2232086"."TIMESHEET_UPDATE" 
( PARAM_TIMESHEET_ID IN VARCHAR2,
   PARAM_NUMBER_HOURS_WORKED IN NUMBER
) AS 
BEGIN
  /* 2023-11-10  NATALIA HERRERA( 2232086)
   CREATE UPDATE PROCEDURE FOR TIMESHEET TABLE
  */
  
  update TIMESHEET
    set NUMBER_HOURS_WORKED = PARAM_NUMBER_HOURS_WORKED
    where timesheet_id = PARAM_TIMESHEET_ID;
    COMMIT;
    
END TIMESHEET_UPDATE;

/
--------------------------------------------------------
--  DDL for Function FC_CALC_PAYCHECK
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_HERRERA_2232086"."FC_CALC_PAYCHECK" 
(
  PARAM_SALARY IN NUMBER 
, PARAM_HOUR_AMOUNT IN NUMBER 
, PARAM_INSURANCE_FEE IN NUMBER 
) RETURN NUMBER AS 
BEGIN
  /* 
  2023-11-17  NATALIA HERRERA( 2232086)
  CREATE FUNCTION FOR CALCULATION OF FEE INSURANCE */
 
    RETURN (PARAM_SALARY - PARAM_INSURANCE_FEE) * PARAM_HOUR_AMOUNT;
 
END FC_CALC_PAYCHECK;

/
--------------------------------------------------------
--  DDL for Function FC_REPORT_STUDENT_ROWS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_HERRERA_2232086"."FC_REPORT_STUDENT_ROWS" (
    p_student_id IN VARCHAR2
) RETURN type_report_student_table
    PIPELINED
AS
BEGIN
-- 2023-11-10 NATALIA HERRERA( 2232086)
-- CREATE FUNCTION WITH INNER JOIN
--  2023-11-24 NATALIA HERRERA( 2232086)
-- add allergies
    FOR nh IN (
        SELECT
            r.report_id,
            r.grade,
            r.comments,
            r.create_date_time AS report_create_date_time,
            r.modify_date_time AS report_modify_date_time,
            r.dates_exam,
            s.student_id,
            s.lastname         AS student_lastname,
            s.firstname        AS student_firstname,
            s.student_number,
            s.address,
            s.city,
            s.postal_code,
            s.create_date_time AS student_create_date_time,
            s.modify_date_time AS student_modify_date_time,
            s.numbers_of_tries,
            s.allergies,
            t.teacher_id,
            t.lastname         AS teacher_lastname,
            t.firstname        AS teacher_firstname,
            t.email,
            t.salary,
            t.create_date_time AS teacher_create_date_time,
            t.modify_date_time AS teacher_modify_date_time,
            t.insurance_number,
            t.insurances_fee,
            t.insurance_to_pay,
            c.course_id,
            c.course_name,
            c.course_code,
            c.description,
            c.create_date_time AS course_create_date_time,
            c.modify_date_time AS course_modify_date_time
        FROM
                 reports r
            INNER JOIN students s ON ( r.student_id = s.student_id
                                       AND s.student_id = p_student_id )
            INNER JOIN teachers t ON ( r.teacher_id = t.teacher_id )
            INNER JOIN courses  c ON ( r.course_id = c.course_id )
        ORDER BY
            r.create_date_time DESC
    ) LOOP
        PIPE ROW ( type_report_student_row(nh.report_id, nh.grade, nh.comments, nh.report_create_date_time, nh.report_modify_date_time
        ,
                                          nh.dates_exam, nh.student_id, nh.student_lastname, nh.student_firstname, nh.student_number,
                                          nh.address, nh.city, nh.postal_code, nh.student_create_date_time, nh.student_modify_date_time
                                          ,
                                          nh.numbers_of_tries, nh.allergies, nh.teacher_id, nh.teacher_lastname, nh.teacher_firstname, nh.email,
                                          nh.salary, nh.teacher_create_date_time, nh.teacher_modify_date_time, nh.insurance_number, nh.insurances_fee
                                          ,
                                          nh.insurance_to_pay, nh.course_id, nh.course_name, nh.course_code, nh.description,
                                          nh.course_create_date_time, nh.course_modify_date_time) );
    END LOOP;

    RETURN;
END fc_report_student_rows;

/
--------------------------------------------------------
--  DDL for Function FC_STUDENTS_ALL_ROWS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_HERRERA_2232086"."FC_STUDENTS_ALL_ROWS" RETURN type_students_table
    PIPELINED
AS
BEGIN
/* 2023-11-01  NATALIA HERRERA( 2232086)
    CREATE FUNCTION ALL ROWS
     2023-11-02  NATALIA HERRERA( 2232086)
     UPDATE NAME FOR LASTNAME
     2023-11-24  NATALIA HERRERA( 2232086)
     UPDATE ALLERGIES
   */
    FOR nh IN (
        SELECT
            student_id,
            lastname,
            firstname,
            address,
            city,
            postal_code,
            student_number,
            create_date_time,
            modify_date_time,
            allergies
        FROM
            students
    ) LOOP
        PIPE ROW ( type_students_row(nh.student_id, nh.lastname, nh.firstname, nh.address, nh.city,
                                    nh.postal_code, nh.student_number, nh.create_date_time, nh.modify_date_time, nh.allergies) );
    END LOOP;

    RETURN;
END fc_students_all_rows;

/
--------------------------------------------------------
--  DDL for Function FC_STUDENTS_ONE_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_HERRERA_2232086"."FC_STUDENTS_ONE_ROW" (
    param_student_id IN VARCHAR2
) RETURN type_students_table
    PIPELINED
AS
BEGIN
/* 2023-11-01  NATALIA HERRERA( 2232086)
    CREATE FUNCTION ONE ROWS
    2023-11-02  NATALIA HERRERA( 2232086)
    CHANGE THE NAME FOR LASTNAME
    2023-11-24  NATALIA HERRERA( 2232086)
    update allergies column*/
    FOR nh IN (
        SELECT
            student_id,
            lastname,
            firstname,
            address,
            city,
            postal_code,
            student_number,
            create_date_time,
            modify_date_time,
            allergies
        FROM
            students
        WHERE
            student_id = param_student_id
    ) LOOP
        PIPE ROW ( type_students_row(nh.student_id, nh.lastname, nh.firstname, nh.address, nh.city,
                                    nh.postal_code, nh.student_number, nh.create_date_time, nh.modify_date_time, nh.allergies) );
    END LOOP;

    RETURN;
END fc_students_one_row;

/
--------------------------------------------------------
--  DDL for Function FC_TEACHERS_ALL_ROWS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_HERRERA_2232086"."FC_TEACHERS_ALL_ROWS" 
RETURN TYPE_TEACHERS_TABLE PIPELINED AS 
BEGIN
/* 2023-11-01  NATALIA HERRERA( 2232086)
    CREATE FUNCTION ALL ROWS
    2023-11-02  NATALIA HERRERA( 2232086)
    CHANGE THE NAME FOR LASTNAME*/
  FOR NH IN (SELECT * FROM TEACHERS) LOOP
    PIPE ROW (TYPE_TEACHERS_ROW 
                (NH.TEACHER_ID,
                NH.LASTNAME,
                NH.FIRSTNAME,
                NH.EMAIL,
                NH.SALARY,
                NH.CREATE_DATE_TIME,
                NH.MODIFY_DATE_TIME));
  
  END LOOP;
  RETURN;
  
END FC_TEACHERS_ALL_ROWS;

/
--------------------------------------------------------
--  DDL for Function FC_TEACHERS_ONE_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_HERRERA_2232086"."FC_TEACHERS_ONE_ROW" 
(PARAM_TEACHER_ID in varchar2)
RETURN TYPE_TEACHERS_TABLE PIPELINED AS 
BEGIN
/* 2023-11-01  NATALIA HERRERA( 2232086)
    CREATE FUNCTION ONE ROWS
    2023-11-02  NATALIA HERRERA( 2232086)
    CHANGE THE NAME FOR LASTNAME*/
  FOR NH IN (SELECT * FROM TEACHERS WHERE TEACHER_ID = PARAM_TEACHER_ID)
  LOOP
    PIPE ROW (TYPE_TEACHERS_ROW 
                (NH.TEACHER_ID,
                NH.LASTNAME,
                NH.FIRSTNAME,
                NH.EMAIL,
                NH.SALARY,
                NH.CREATE_DATE_TIME,
                NH.MODIFY_DATE_TIME));
  
  END LOOP;
  RETURN;
  
END FC_TEACHERS_ONE_ROW;

/
--------------------------------------------------------
--  DDL for Function FC_TIMESHEET_ONE_ROW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_HERRERA_2232086"."FC_TIMESHEET_ONE_ROW" 
(PARAM_TIMESHEET_ID in varchar2)
RETURN TYPE_TIMESHEET_TABLE PIPELINED AS 
BEGIN
/* 2023-11-10  NATALIA HERRERA( 2232086)
    CREATE FUNCTION ONE ROWS*/
   
  FOR NH IN (SELECT * FROM TIMESHEET WHERE TIMESHEET_ID = PARAM_TIMESHEET_ID)
  LOOP
        PIPE ROW ( type_timesheet_row(
        NH.timesheet_id,
        NH.teacher_id,
        NH.WEEK_NUMBER, 
        NH.year, 
        NH.NUMBER_HOURS_WORKED,
        NH.create_date_time,
        NH.modify_date_time) 
        );
    END LOOP;
  RETURN;
  
END FC_TIMESHEET_ONE_ROW;

/
--------------------------------------------------------
--  DDL for Function FC_TIMESHEET_TEACHER_ROWS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHOOL_HERRERA_2232086"."FC_TIMESHEET_TEACHER_ROWS" (
    param_teacher_id IN VARCHAR2
) RETURN type_timesheet_teacher_table
    PIPELINED
AS
BEGIN
-- 2023-11-10  NATALIA HERRERA( 2232086))   CREATE A NEW FUNCTION
    FOR nh IN (
        SELECT
            timesheet.timesheet_id,
            timesheet.week_number,
            timesheet.year,
            timesheet.number_hours_worked,
            timesheet.create_date_time                                                             AS timesheet_create_datetime,
            timesheet.modify_date_time                                                             AS timesheet_modify_datetime,
            teacher.teacher_id,
            teacher.lastname,
            teacher.firstname,
            teacher.email,
            teacher.salary,
            teacher.create_date_time,
            teacher.modify_date_time,
            teacher.insurance_number,
            teacher.insurance_to_pay,
            teacher.insurances_fee,
            fc_calc_paycheck(teacher.salary, timesheet.number_hours_worked, teacher.insurances_fee) AS paycheck
        FROM
                 timesheet timesheet
            INNER JOIN teachers teacher ON ( timesheet.teacher_id = teacher.teacher_id
                                             AND teacher.teacher_id = param_teacher_id )
        ORDER BY
            timesheet.year,
            timesheet.week_number
    ) LOOP
        PIPE ROW ( 
        type_timesheet_teacher_row(
        nh.timesheet_id,
        nh.week_number, nh.year,
        nh.number_hours_worked, 
        nh.timesheet_create_datetime
        ,
                                             nh.timesheet_modify_datetime, nh.teacher_id, nh.lastname, nh.firstname, nh.email,
                                             nh.salary, nh.create_date_time, nh.modify_date_time, nh.insurance_number, nh.insurances_fee
                                             ,
                                             nh.insurance_to_pay, nh.paycheck) );
    END LOOP;

    RETURN;
END fc_timesheet_teacher_rows;

/
--------------------------------------------------------
--  Constraints for Table COURSES
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."COURSES" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."COURSES" MODIFY ("COURSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."COURSES" MODIFY ("COURSE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."COURSES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."COURSES" MODIFY ("CREATE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."COURSES" MODIFY ("MODIFY_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."COURSES" ADD CONSTRAINT "COURSES_PK" PRIMARY KEY ("COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_HERRERA_2232086"."COURSES" ADD CONSTRAINT "COURSES_COURSE_CODE_UK" UNIQUE ("COURSE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIMESHEET
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."TIMESHEET" MODIFY ("TIMESHEET_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TIMESHEET" MODIFY ("WEEK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TIMESHEET" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TIMESHEET" MODIFY ("NUMBER_HOURS_WORKED" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TIMESHEET" ADD CONSTRAINT "TIMESHEET_PK" PRIMARY KEY ("TIMESHEET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TIMESHEET" ADD CONSTRAINT "TIMESHEET_UK_TEACHER_WEEK" UNIQUE ("TEACHER_ID", "WEEK_NUMBER", "YEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MODIFICATIONS_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY" MODIFY ("MODIFICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY" ADD CONSTRAINT "MODIFICATIONS_HISTORY_PK" PRIMARY KEY ("MODIFICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" MODIFY ("CREATE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" MODIFY ("MODIFY_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" ADD CONSTRAINT "STUDENTS_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."STUDENTS" ADD CONSTRAINT "STUDENTS_STUDENTNUMBER_UK" UNIQUE ("STUDENT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEACHERS
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" MODIFY ("TEACHER_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" ADD CONSTRAINT "TEACHERS_PK" PRIMARY KEY ("TEACHER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" MODIFY ("CREATE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" MODIFY ("MODIFY_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" MODIFY ("INSURANCES_FEE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."TEACHERS" ADD CONSTRAINT "TEACHERS_INSURANCE_NUMBER_CHK" CHECK (LENGTH(INSURANCE_NUMBER)=9) ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" MODIFY ("TEACHER_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" ADD CONSTRAINT "REPORTS_PK" PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" ADD CONSTRAINT "REPORTS_GRADE_CHK" CHECK (GRADE >=0 AND GRADE <=100) ENABLE;
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" MODIFY ("CREATE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" MODIFY ("MODIFY_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" MODIFY ("COMMENTS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" ADD CONSTRAINT "REPORTS_STUDENT_COURSE_ID_UK" UNIQUE ("STUDENT_ID", "COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODIFICATIONS_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."MODIFICATIONS_HISTORY" ADD CONSTRAINT "MODIFICATIONS_HISTORY_REPORT_ID_FK" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "SCHOOL_HERRERA_2232086"."REPORTS" ("REPORT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" ADD CONSTRAINT "REPORTS_STUDENT_ID_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SCHOOL_HERRERA_2232086"."STUDENTS" ("STUDENT_ID") ENABLE;
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" ADD CONSTRAINT "REPORTS_TEACHER_ID_FK" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "SCHOOL_HERRERA_2232086"."TEACHERS" ("TEACHER_ID") ENABLE;
  ALTER TABLE "SCHOOL_HERRERA_2232086"."REPORTS" ADD CONSTRAINT "REPORTS_COURSE_ID_FK" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "SCHOOL_HERRERA_2232086"."COURSES" ("COURSE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIMESHEET
--------------------------------------------------------

  ALTER TABLE "SCHOOL_HERRERA_2232086"."TIMESHEET" ADD CONSTRAINT "TIMESHEET_FK_TEACHER_ID" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "SCHOOL_HERRERA_2232086"."TEACHERS" ("TEACHER_ID") ENABLE;
