SERVEROUTPUT ON

--TEST FUNCTIONS

--CALCULATIONS PAYMENT
SELECT FC_CALC_PAYCHECK (30,15,20) AS paycheck FROM DUAL;
-- REPORT STUDENT SELECT
SELECT * FROM TABLE (FC_REPORT_STUDENT_ROWS('A8A9E455244040789BE43D20D25300B5'));
-- STUDENT ALL ROWS SELECT
SELECT * FROM TABLE (FC_STUDENTS_ALL_ROWS());
-- STUDENT ONE ROW SELECT
SELECT * FROM TABLE (FC_STUDENTS_ONE_ROW('A8A9E455244040789BE43D20D25300B5'));
-- TEACHER ALL ROWS SELECT
SELECT * FROM TABLE (FC_TEACHERS_ALL_ROWS());
-- TEACHER ONE ROW SELECT
SELECT * FROM TABLE (FC_TEACHERS_ONE_ROW('DAAF3707D4DA45A3B917841AB553723E'));
-- TIMESHEET ONE ROW SELECT
SELECT * FROM TABLE (FC_TIMESHEET_ONE_ROW('83FC9CFB089A4D1BAE8F8C2FED9A91D3'));
-- TIMESHEET ONE ROW SELECT
SELECT * FROM TABLE (FC_TIMESHEET_TEACHER_ROWS('DAAF3707D4DA45A3B917841AB553723E'));


--TEST PROCEDURES

--STUDENT INSERT
/
DECLARE
  PARAM_LASTNAME VARCHAR2(200);
  PARAM_FIRSTNAME VARCHAR2(200);
  PARAM_ADDRESS VARCHAR2(200);
  PARAM_CITY VARCHAR2(200);
  PARAM_POSTAL_CODE VARCHAR2(200);
  PARAM_ALLERGIES VARCHAR2(200);
BEGIN
  PARAM_LASTNAME := 'GOMEZ';
  PARAM_FIRSTNAME := 'HAMILTON';
  PARAM_ADDRESS := '6777 MOUNTAIN SIGHTS';
  PARAM_CITY := 'MONTREAL';
  PARAM_POSTAL_CODE := '1H1H2H';
  PARAM_ALLERGIES := 'PEANUTS';

  STUDENTS_INSERT(
    PARAM_LASTNAME => PARAM_LASTNAME,
    PARAM_FIRSTNAME => PARAM_FIRSTNAME,
    PARAM_ADDRESS => PARAM_ADDRESS,
    PARAM_CITY => PARAM_CITY,
    PARAM_POSTAL_CODE => PARAM_POSTAL_CODE,
    PARAM_ALLERGIES => PARAM_ALLERGIES
  );

END;

/

--STUDENT UPDATE
/
DECLARE
  PARAM_STUDENT_ID VARCHAR2(200);
  PARAM_LASTNAME VARCHAR2(200);
  PARAM_FIRSTNAME VARCHAR2(200);
  PARAM_ADDRESS VARCHAR2(200);
  PARAM_CITY VARCHAR2(200);
  PARAM_POSTAL_CODE VARCHAR2(200);
  PARAM_ALLERGIES VARCHAR2(200);
BEGIN
  PARAM_STUDENT_ID := '2B30694B76754DFD8FFE30587E089FA1';
  PARAM_LASTNAME := 'PENHA';
  PARAM_FIRSTNAME := 'NELSON';
  PARAM_ADDRESS := '4452 Snowdown';
  PARAM_CITY := 'MONTREAL';
  PARAM_POSTAL_CODE := '1D2D3D';
  PARAM_ALLERGIES := 'MILK';

  STUDENTS_UPDATE(
    PARAM_STUDENT_ID => PARAM_STUDENT_ID,
    PARAM_LASTNAME => PARAM_LASTNAME,
    PARAM_FIRSTNAME => PARAM_FIRSTNAME,
    PARAM_ADDRESS => PARAM_ADDRESS,
    PARAM_CITY => PARAM_CITY,
    PARAM_POSTAL_CODE => PARAM_POSTAL_CODE,
    PARAM_ALLERGIES => PARAM_ALLERGIES
  );
END;
/

--STUDENT DELETE
/
DECLARE
  PARAM_STUDENT_ID VARCHAR2(200);
BEGIN
  PARAM_STUDENT_ID := 'C58904035F764716A8A98D3AFD3C1F6D';

  STUDENTS_DELETE(
    PARAM_STUDENT_ID => PARAM_STUDENT_ID
  );
END;

/

--TEACHER INSERT
/
DECLARE
  PARAM_LASTNAME VARCHAR2(200);
  PARAM_FIRSTNAME VARCHAR2(200);
  PARAM_EMAIL VARCHAR2(200);
  PARAM_SALARY NUMBER;
  PARAM_INSURANCE_NUMBER NUMBER;
  PARAM_INSURANCES_FEE NUMBER;
BEGIN
  PARAM_LASTNAME := 'ELRIC';
  PARAM_FIRSTNAME := 'EDWARD';
  PARAM_EMAIL := 'ELRIC@LASALLE.CA';
  PARAM_SALARY := 100;
  PARAM_INSURANCE_NUMBER := 275362141;
  PARAM_INSURANCES_FEE := 2.58;

  TEACHERS_INSERT(
    PARAM_LASTNAME => PARAM_LASTNAME,
    PARAM_FIRSTNAME => PARAM_FIRSTNAME,
    PARAM_EMAIL => PARAM_EMAIL,
    PARAM_SALARY => PARAM_SALARY,
    PARAM_INSURANCE_NUMBER => PARAM_INSURANCE_NUMBER,
    PARAM_INSURANCES_FEE => PARAM_INSURANCES_FEE
  );

END;
/

--TEACHER UPDATE
/
DECLARE
  PARAM_TEACHER_ID VARCHAR2(200);
  PARAM_LASTNAME VARCHAR2(200);
  PARAM_FIRSTNAME VARCHAR2(200);
  PARAM_EMAIL VARCHAR2(200);
  PARAM_SALARY NUMBER;
BEGIN
  PARAM_TEACHER_ID := 'F18A6562C33E435998496862DBB9472D';
  PARAM_LASTNAME := 'Saint';
  PARAM_FIRSTNAME := 'Patrick';
  PARAM_EMAIL := 'Saint@lasalle.ca';
  PARAM_SALARY := 150;

  TEACHERS_UPDATE(
    PARAM_TEACHER_ID => PARAM_TEACHER_ID,
    PARAM_LASTNAME => PARAM_LASTNAME,
    PARAM_FIRSTNAME => PARAM_FIRSTNAME,
    PARAM_EMAIL => PARAM_EMAIL,
    PARAM_SALARY => PARAM_SALARY
  );
END;
/

--TEACHER DELETE
/
DECLARE
  PARAM_TEACHER_ID VARCHAR2(200);
BEGIN
  PARAM_TEACHER_ID :='B57151A1A74F410C821D9B0A508498C6';

  TEACHERS_DELETE(
    PARAM_TEACHER_ID => PARAM_TEACHER_ID
  );
END;
/

--REPORTS INSERT
/
DECLARE
  PARAM_STUDENT_ID VARCHAR2(200);
  PARAM_TEACHER_ID VARCHAR2(200);
  PARAM_GRADE NUMBER;
  PARAM_COMMENTS VARCHAR2(200);
  PARAM_DATES_EXAM DATE;
  PARAM_COURSE_ID VARCHAR2(200);
BEGIN
  PARAM_STUDENT_ID := '20D41AB7204045DD9ADD6A6A17832479';
  PARAM_TEACHER_ID := 'DAAF3707D4DA45A3B917841AB553723E';
  PARAM_GRADE := 99;
  PARAM_COMMENTS := 'EXCELENT';
  PARAM_DATES_EXAM := to_date('2023-10-20','yyyy-MM-dd');
  PARAM_COURSE_ID := '086F206ED41E46968C1686300D181623';

  REPORTS_INSERT(
    PARAM_STUDENT_ID => PARAM_STUDENT_ID,
    PARAM_TEACHER_ID => PARAM_TEACHER_ID,
    PARAM_GRADE => PARAM_GRADE,
    PARAM_COMMENTS => PARAM_COMMENTS,
    PARAM_DATES_EXAM => PARAM_DATES_EXAM,
    PARAM_COURSE_ID => PARAM_COURSE_ID
  );
END;
/


--REPORTS UPDATE
/
DECLARE
  PARAM_REPORT_ID VARCHAR2(200);
  PARAM_GRADE NUMBER;
  PARAM_COMMENTS VARCHAR2(200);
  PARAM_DATES_EXAM DATE;
BEGIN
  PARAM_REPORT_ID := '62B378BC48754F40A3D7FCD21D9C1462';
  PARAM_GRADE := 83;
  PARAM_COMMENTS := 'GOOD';
  PARAM_DATES_EXAM := to_date('2023-10-15','yyyy-MM-dd');

  REPORT_UPDATE(
    PARAM_REPORT_ID => PARAM_REPORT_ID,
    PARAM_GRADE => PARAM_GRADE,
    PARAM_COMMENTS => PARAM_COMMENTS,
    PARAM_DATES_EXAM => PARAM_DATES_EXAM
  );
 
END;
/

--REPORTS DELETE
/
DECLARE
  PARAM_STUDENT_ID VARCHAR2(200);
  PARAM_COURSE_ID VARCHAR2(200);
BEGIN
  PARAM_STUDENT_ID := '20D41AB7204045DD9ADD6A6A17832479';
  PARAM_COURSE_ID := '086F206ED41E46968C1686300D181623';

  REPORTS_DELETE(
    PARAM_STUDENT_ID => PARAM_STUDENT_ID,
    PARAM_COURSE_ID => PARAM_COURSE_ID
  );
 
END;
/

--REPORT COUNT GRADES
/
DECLARE
  PARAM_STUDENT_ID VARCHAR2(200);
  PARAM_COUNT NUMBER;
BEGIN
  PARAM_STUDENT_ID := '366040709E984E4EA19B40DB66F28D7E';

  REPORT_COUNT_GRADE_STUDENT(
    PARAM_STUDENT_ID => PARAM_STUDENT_ID,
    PARAM_COUNT => PARAM_COUNT
  );
 
DBMS_OUTPUT.PUT_LINE('PARAM_COUNT = count grades' || PARAM_COUNT);

  :PARAM_COUNT := PARAM_COUNT;

END;
/

--COURSE INSERT
/
DECLARE
  PARAM_COURSE_NAME VARCHAR2(200);
  PARAM_COURSE_CODE VARCHAR2(200);
  PARAM_DESCRIPTION VARCHAR2(200);
  PARAM_COURSE_ID VARCHAR2(200);
BEGIN
  PARAM_COURSE_NAME := 'INTRODUCTION LINUX';
  PARAM_COURSE_CODE := '420-ITL-AS';
  PARAM_DESCRIPTION := 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.';

  COURSE_INSERT(
    PARAM_COURSE_NAME => PARAM_COURSE_NAME,
    PARAM_COURSE_CODE => PARAM_COURSE_CODE,
    PARAM_DESCRIPTION => PARAM_DESCRIPTION,
    PARAM_COURSE_ID => PARAM_COURSE_ID
  );

    DBMS_OUTPUT.PUT_LINE('PARAM_COURSE_ID = course' || PARAM_COURSE_ID);

  :PARAM_COURSE_ID := PARAM_COURSE_ID;

END;
/

--COURSE DELETE
/

DECLARE
  P_COURSE_ID VARCHAR2(200);
BEGIN
  P_COURSE_ID := 1;

  COURSE_DELETE(
    P_COURSE_ID => P_COURSE_ID
  );

END;


/

--TIMESHEET INSERT
/
DECLARE
  PARAM_TEACHER_ID VARCHAR2(200);
  PARAM_WEEK_NUMBER NUMBER;
  PARAM_YEAR NUMBER;
  PARAM_NUMBER_HOURS_WORKED NUMBER;
BEGIN
  PARAM_TEACHER_ID := '06A179E27A3844A781E4516751FD0727';
  PARAM_WEEK_NUMBER := 3;
  PARAM_YEAR := 2023;
  PARAM_NUMBER_HOURS_WORKED := 15;

  TIMESHEET_INSERT(
    PARAM_TEACHER_ID => PARAM_TEACHER_ID,
    PARAM_WEEK_NUMBER => PARAM_WEEK_NUMBER,
    PARAM_YEAR => PARAM_YEAR,
    PARAM_NUMBER_HOURS_WORKED => PARAM_NUMBER_HOURS_WORKED
  );

END;

/


--TIMESHEET UPDATE
/
DECLARE
  PARAM_TIMESHEET_ID VARCHAR2(200);
  PARAM_NUMBER_HOURS_WORKED NUMBER;
BEGIN
  PARAM_TIMESHEET_ID := '63324E1CA5E4472D85A958966F849267';
  PARAM_NUMBER_HOURS_WORKED := 30;

  TIMESHEET_UPDATE(
    PARAM_TIMESHEET_ID => PARAM_TIMESHEET_ID,
    PARAM_NUMBER_HOURS_WORKED => PARAM_NUMBER_HOURS_WORKED
  );

END;

/

--TIMESHEET DELETE
/
DECLARE
  PARAM_TEACHER_ID VARCHAR2(200);
  PARAM_WEEK_NUMBER NUMBER;
  PARAM_YEAR NUMBER;
BEGIN
  PARAM_TEACHER_ID :='06A179E27A3844A781E4516751FD0727';
  PARAM_WEEK_NUMBER := 3;
  PARAM_YEAR := 2023;

  TIMESHEET_DELETE(
    PARAM_TEACHER_ID => PARAM_TEACHER_ID,
    PARAM_WEEK_NUMBER => PARAM_WEEK_NUMBER,
    PARAM_YEAR => PARAM_YEAR
  );

END;

/
